version: '3.4'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
    authentication_service:
        image: authentication_service
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "7001:3001"
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017
            - MONGO_HOST=mongo
            - MONGO_AUTH_SOURCE=authentication-server
        restart: always
